version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    labels:
      - "dependencies"
      - "maintenance"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
    - tiksn
    assignees:
    - tiksn
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "dependencies"
      - "maintenance"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - tiksn
    assignees:
      - tiksn
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "maintenance"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    reviewers:
      - "tiksn"
    assignees:
      - "tiksn"
